// Country dataset used to build flag-guessing questions.
//
// Each entry: { code, name, continent, fact }
//   code       - ISO 3166-1 alpha-2, lowercase. Used to build the flag URL
//                via flagcdn.com (e.g. https://flagcdn.com/w320/fr.png).
//   name       - Display name shown to players.
//   continent  - One of: Africa, Asia, Europe, North America, South America, Oceania.
//                Used to pick same-continent distractors so wrong options feel plausible.
//   fact       - Short, fun trivia line shown between rounds.
//
// The list is intentionally a single static array — no DB, no fetch. It loads
// once at server start and is shared by solo + multiplayer question builders.

const COUNTRIES = [
  // --- Africa ---
  { code: "dz", name: "Algeria",        continent: "Africa", fact: "Algeria is the largest country in Africa by area." },
  { code: "ao", name: "Angola",         continent: "Africa", fact: "Angola's flag features a machete crossed with half a gear." },
  { code: "bj", name: "Benin",          continent: "Africa", fact: "Benin is the birthplace of the Vodun (Voodoo) religion." },
  { code: "bw", name: "Botswana",       continent: "Africa", fact: "Botswana's flag's blue stripe represents water — vital in this dry land." },
  { code: "bf", name: "Burkina Faso",   continent: "Africa", fact: "Burkina Faso means 'Land of Incorruptible People'." },
  { code: "bi", name: "Burundi",        continent: "Africa", fact: "Burundi has one of the world's smallest economies — and great drummers." },
  { code: "cv", name: "Cape Verde",     continent: "Africa", fact: "Cape Verde is an archipelago of 10 volcanic islands." },
  { code: "cm", name: "Cameroon",       continent: "Africa", fact: "Cameroon is nicknamed 'Africa in miniature' for its diverse geography." },
  { code: "cf", name: "Central African Republic", continent: "Africa", fact: "Its flag combines French and Pan-African colors with a single yellow star." },
  { code: "td", name: "Chad",           continent: "Africa", fact: "Chad's flag is nearly identical to Romania's — a long-standing friendly dispute." },
  { code: "km", name: "Comoros",        continent: "Africa", fact: "Comoros means 'islands of the moon' in Arabic." },
  { code: "cg", name: "Republic of the Congo", continent: "Africa", fact: "Brazzaville, its capital, faces Kinshasa across the Congo River — the world's closest capitals." },
  { code: "cd", name: "DR Congo",       continent: "Africa", fact: "The Democratic Republic of the Congo is home to the world's second-largest rainforest." },
  { code: "ci", name: "Ivory Coast",    continent: "Africa", fact: "Ivory Coast's flag is the mirror image of Ireland's." },
  { code: "dj", name: "Djibouti",       continent: "Africa", fact: "Djibouti contains Lake Assal — the lowest point in Africa." },
  { code: "eg", name: "Egypt",          continent: "Africa", fact: "Egypt's flag features the Eagle of Saladin in its center." },
  { code: "gq", name: "Equatorial Guinea", continent: "Africa", fact: "It's the only African country with Spanish as an official language." },
  { code: "er", name: "Eritrea",        continent: "Africa", fact: "Eritrea's flag features an olive wreath — a nod to its long fight for independence." },
  { code: "sz", name: "Eswatini",       continent: "Africa", fact: "Formerly Swaziland — its flag features a Nguni shield and spears." },
  { code: "et", name: "Ethiopia",       continent: "Africa", fact: "Ethiopia is the only African country never formally colonized." },
  { code: "ga", name: "Gabon",          continent: "Africa", fact: "Gabon's flag is one of the few in the world with horizontal stripes of green, yellow, and blue." },
  { code: "gm", name: "Gambia",         continent: "Africa", fact: "The Gambia is the smallest country in mainland Africa." },
  { code: "gh", name: "Ghana",          continent: "Africa", fact: "Ghana was the first sub-Saharan African country to gain independence (1957)." },
  { code: "gn", name: "Guinea",         continent: "Africa", fact: "Guinea's flag mirrors Mali's, just with the colors reversed." },
  { code: "gw", name: "Guinea-Bissau",  continent: "Africa", fact: "Guinea-Bissau's flag features a single black star on a red stripe." },
  { code: "ke", name: "Kenya",          continent: "Africa", fact: "Kenya's flag features a Maasai shield and crossed spears." },
  { code: "ls", name: "Lesotho",        continent: "Africa", fact: "Lesotho is one of only three countries entirely surrounded by another country." },
  { code: "lr", name: "Liberia",        continent: "Africa", fact: "Liberia's flag closely resembles the US flag — it was founded by freed American slaves." },
  { code: "ly", name: "Libya",          continent: "Africa", fact: "From 1977 to 2011, Libya's flag was a plain green rectangle — the simplest in the world." },
  { code: "mg", name: "Madagascar",     continent: "Africa", fact: "Madagascar is home to lemurs found nowhere else on Earth." },
  { code: "mw", name: "Malawi",         continent: "Africa", fact: "Malawi's flag features a rising sun — symbolizing the dawn of freedom." },
  { code: "ml", name: "Mali",           continent: "Africa", fact: "Timbuktu, in Mali, was once a world-renowned center of Islamic scholarship." },
  { code: "mr", name: "Mauritania",     continent: "Africa", fact: "Mauritania's flag features a crescent moon and star with two red stripes added in 2017." },
  { code: "mu", name: "Mauritius",      continent: "Africa", fact: "Mauritius is the only country whose flag has four horizontal stripes." },
  { code: "ma", name: "Morocco",        continent: "Africa", fact: "Morocco's flag features a green pentagram — the Seal of Solomon." },
  { code: "mz", name: "Mozambique",     continent: "Africa", fact: "Mozambique is the only national flag with a modern firearm — an AK-47." },
  { code: "na", name: "Namibia",        continent: "Africa", fact: "Namibia's flag features a 12-rayed sun representing energy and life." },
  { code: "ne", name: "Niger",          continent: "Africa", fact: "Niger's flag features an orange disc — said to represent the Sahara sun." },
  { code: "ng", name: "Nigeria",        continent: "Africa", fact: "Nigeria is Africa's most populous country with over 220 million people." },
  { code: "rw", name: "Rwanda",         continent: "Africa", fact: "Rwanda is famous for mountain gorilla conservation in Volcanoes National Park." },
  { code: "st", name: "São Tomé and Príncipe", continent: "Africa", fact: "It's Africa's second-smallest country — and a chocolate paradise." },
  { code: "sn", name: "Senegal",        continent: "Africa", fact: "Senegal's flag features a green star — a symbol of hope and Islam." },
  { code: "sc", name: "Seychelles",     continent: "Africa", fact: "Seychelles' flag has five stripes radiating from one corner — unique in the world." },
  { code: "sl", name: "Sierra Leone",   continent: "Africa", fact: "Sierra Leone means 'Lion Mountains' in Portuguese." },
  { code: "so", name: "Somalia",        continent: "Africa", fact: "Somalia's flag's blue is inspired by the UN flag." },
  { code: "za", name: "South Africa",   continent: "Africa", fact: "South Africa has three capital cities: Pretoria, Cape Town, and Bloemfontein." },
  { code: "ss", name: "South Sudan",    continent: "Africa", fact: "South Sudan is the world's youngest country, founded in 2011." },
  { code: "sd", name: "Sudan",          continent: "Africa", fact: "Sudan has more pyramids than Egypt — over 200 of them." },
  { code: "tz", name: "Tanzania",       continent: "Africa", fact: "Mount Kilimanjaro, Africa's highest peak, is in Tanzania." },
  { code: "tg", name: "Togo",           continent: "Africa", fact: "Togo's flag is one of only a few designed in a 1.618 golden ratio." },
  { code: "tn", name: "Tunisia",        continent: "Africa", fact: "Tunisia's flag has been used in similar form since 1831." },
  { code: "ug", name: "Uganda",         continent: "Africa", fact: "Uganda's flag features the grey crowned crane — its national bird." },
  { code: "zm", name: "Zambia",         continent: "Africa", fact: "Zambia is the only country to feature its national bird (eagle) on its flag's right side." },
  { code: "zw", name: "Zimbabwe",       continent: "Africa", fact: "Zimbabwe's flag features a soapstone bird modeled on those found at Great Zimbabwe ruins." },

  // --- Asia ---
  { code: "af", name: "Afghanistan",    continent: "Asia", fact: "Afghanistan has changed its flag more than any country in the past century." },
  { code: "am", name: "Armenia",        continent: "Asia", fact: "Armenia was the first country to adopt Christianity as its state religion (301 AD)." },
  { code: "az", name: "Azerbaijan",     continent: "Asia", fact: "Azerbaijan is known as the 'Land of Fire' for its natural gas vents." },
  { code: "bh", name: "Bahrain",        continent: "Asia", fact: "Bahrain's flag's five white triangles represent the five pillars of Islam." },
  { code: "bd", name: "Bangladesh",     continent: "Asia", fact: "Bangladesh's flag features a red disc on green — said to evoke a sun rising over a verdant land." },
  { code: "bt", name: "Bhutan",         continent: "Asia", fact: "Bhutan is the only country with a dragon on its flag — the Druk." },
  { code: "bn", name: "Brunei",         continent: "Asia", fact: "Brunei's flag is one of the most intricate, with Arabic script in its center." },
  { code: "kh", name: "Cambodia",       continent: "Asia", fact: "Cambodia is the only country to feature a building (Angkor Wat) on its flag." },
  { code: "cn", name: "China",          continent: "Asia", fact: "The four small stars on China's flag represent the four social classes." },
  { code: "cy", name: "Cyprus",         continent: "Asia", fact: "Cyprus is one of only two countries (with Kosovo) whose flag depicts its own map." },
  { code: "ge", name: "Georgia",        continent: "Asia", fact: "Georgia's flag features five red crosses — the Five Cross flag dates to medieval times." },
  { code: "in", name: "India",          continent: "Asia", fact: "India's flag features the Ashoka Chakra — a 24-spoked wheel representing dharma." },
  { code: "id", name: "Indonesia",      continent: "Asia", fact: "Indonesia's flag is identical to Monaco's — only the proportions differ." },
  { code: "ir", name: "Iran",           continent: "Asia", fact: "Iran's flag features the word 'Allah' written 22 times along its stripes." },
  { code: "iq", name: "Iraq",           continent: "Asia", fact: "Iraq's flag features the takbir — 'God is the greatest' — in green Arabic script." },
  { code: "il", name: "Israel",         continent: "Asia", fact: "Israel's flag's design is based on the traditional Jewish prayer shawl (tallit)." },
  { code: "jp", name: "Japan",          continent: "Asia", fact: "Japan's flag is officially called Nisshōki — the 'sun-mark flag'." },
  { code: "jo", name: "Jordan",         continent: "Asia", fact: "Jordan's flag's seven-pointed star represents the seven verses of Al-Fatiha." },
  { code: "kz", name: "Kazakhstan",     continent: "Asia", fact: "Kazakhstan is the world's largest landlocked country." },
  { code: "kw", name: "Kuwait",         continent: "Asia", fact: "Kuwait's flag uses the Pan-Arab colors with a unique trapezoidal design." },
  { code: "kg", name: "Kyrgyzstan",     continent: "Asia", fact: "Kyrgyzstan's flag features a 40-rayed sun and a crown of a yurt." },
  { code: "la", name: "Laos",           continent: "Asia", fact: "Laos' flag features a white disc symbolizing the moon over the Mekong River." },
  { code: "lb", name: "Lebanon",        continent: "Asia", fact: "Lebanon's flag features a cedar tree — mentioned 75 times in the Bible." },
  { code: "my", name: "Malaysia",       continent: "Asia", fact: "Malaysia's flag's 14 stripes represent its 13 states plus the federal government." },
  { code: "mv", name: "Maldives",       continent: "Asia", fact: "The Maldives is the world's lowest-lying country — averaging just 1.5m above sea level." },
  { code: "mn", name: "Mongolia",       continent: "Asia", fact: "Mongolia's flag features the Soyombo — a complex symbol of fire, sun, and moon." },
  { code: "mm", name: "Myanmar",        continent: "Asia", fact: "Myanmar adopted its current flag in 2010 — yellow, green, red with a white star." },
  { code: "np", name: "Nepal",          continent: "Asia", fact: "Nepal has the world's only non-rectangular national flag." },
  { code: "kp", name: "North Korea",    continent: "Asia", fact: "North Korea's flag features a red star inside a white disc." },
  { code: "om", name: "Oman",           continent: "Asia", fact: "Oman's flag features the national emblem of crossed swords and a khanjar dagger." },
  { code: "pk", name: "Pakistan",       continent: "Asia", fact: "Pakistan's flag's white stripe represents religious minorities." },
  { code: "ps", name: "Palestine",      continent: "Asia", fact: "Palestine's flag uses the Pan-Arab colors and was first raised in 1916." },
  { code: "ph", name: "Philippines",    continent: "Asia", fact: "The Philippines flips its flag upside down during wartime — red on top." },
  { code: "qa", name: "Qatar",          continent: "Asia", fact: "Qatar's flag is the only national flag whose width is more than twice its height." },
  { code: "sa", name: "Saudi Arabia",   continent: "Asia", fact: "Saudi Arabia's flag features the Shahada — and is never flown at half-mast out of respect." },
  { code: "sg", name: "Singapore",      continent: "Asia", fact: "Singapore's flag's five stars stand for democracy, peace, progress, justice, and equality." },
  { code: "kr", name: "South Korea",    continent: "Asia", fact: "South Korea's flag features the taegeuk — symbolizing the balance of opposites." },
  { code: "lk", name: "Sri Lanka",      continent: "Asia", fact: "Sri Lanka's flag features a golden lion holding a sword." },
  { code: "sy", name: "Syria",          continent: "Asia", fact: "Syria's flag uses the Pan-Arab Liberation colors, with two green stars." },
  { code: "tw", name: "Taiwan",         continent: "Asia", fact: "Taiwan's flag features a 'White Sun in a Blue Sky' — a 12-rayed sun." },
  { code: "tj", name: "Tajikistan",     continent: "Asia", fact: "Tajikistan's flag features a golden crown with seven stars." },
  { code: "th", name: "Thailand",       continent: "Asia", fact: "Thailand's flag is called the Trairanga — three colors with five horizontal stripes." },
  { code: "tl", name: "Timor-Leste",    continent: "Asia", fact: "Timor-Leste gained independence in 2002 — one of the world's youngest nations." },
  { code: "tr", name: "Turkey",         continent: "Asia", fact: "Turkey's flag — Ay-yıldız — features a star and crescent dating back to the Ottoman Empire." },
  { code: "tm", name: "Turkmenistan",   continent: "Asia", fact: "Turkmenistan has the world's most intricate national flag, with five carpet patterns." },
  { code: "ae", name: "United Arab Emirates", continent: "Asia", fact: "The UAE's flag uses the Pan-Arab colors adopted in 1971 at the federation's founding." },
  { code: "uz", name: "Uzbekistan",     continent: "Asia", fact: "Uzbekistan's flag features a crescent moon and 12 stars — one for each zodiac sign." },
  { code: "vn", name: "Vietnam",        continent: "Asia", fact: "Vietnam's flag — the 'Yellow Star Flag' — was adopted in 1945." },
  { code: "ye", name: "Yemen",          continent: "Asia", fact: "Yemen's flag is the simplest of the Arab flags — just three horizontal stripes." },

  // --- Europe ---
  { code: "al", name: "Albania",        continent: "Europe", fact: "Albania's flag features a black double-headed eagle on red — dating to the 15th century." },
  { code: "ad", name: "Andorra",        continent: "Europe", fact: "Andorra is co-ruled by the President of France and a Spanish bishop." },
  { code: "at", name: "Austria",        continent: "Europe", fact: "Austria's flag is one of the world's oldest, said to date back to 1191." },
  { code: "by", name: "Belarus",        continent: "Europe", fact: "Belarus' flag features a traditional decorative pattern on the hoist side." },
  { code: "be", name: "Belgium",        continent: "Europe", fact: "Belgium's vertical tricolor was inspired by France's flag during the 1830 revolution." },
  { code: "ba", name: "Bosnia and Herzegovina", continent: "Europe", fact: "Bosnia's flag's stars and triangle were chosen by the UN in 1998." },
  { code: "bg", name: "Bulgaria",       continent: "Europe", fact: "Bulgaria's flag's green stripe — unusual in Europe — represents its agricultural wealth." },
  { code: "hr", name: "Croatia",        continent: "Europe", fact: "Croatia's flag features the Šahovnica — a red-and-white checkerboard from medieval times." },
  { code: "cz", name: "Czechia",        continent: "Europe", fact: "Czechia's flag was inherited from Czechoslovakia after the 1993 Velvet Divorce." },
  { code: "dk", name: "Denmark",        continent: "Europe", fact: "Denmark's Dannebrog is the oldest continuously used national flag — since 1219." },
  { code: "ee", name: "Estonia",        continent: "Europe", fact: "Estonia's flag's blue, black, white stand for sky, soil, and snow." },
  { code: "fi", name: "Finland",        continent: "Europe", fact: "Finland's flag's blue cross on white was adopted in 1918." },
  { code: "fr", name: "France",         continent: "Europe", fact: "France's tricolor was a symbol of the 1789 revolution and inspired flags worldwide." },
  { code: "de", name: "Germany",        continent: "Europe", fact: "Germany's black-red-gold flag dates back to the early 19th-century unification movement." },
  { code: "gr", name: "Greece",         continent: "Europe", fact: "Greece's flag's nine stripes represent the syllables of 'Eleftheria i Thanatos' — Freedom or Death." },
  { code: "hu", name: "Hungary",        continent: "Europe", fact: "Hungary's flag's red, white, green colors date back to the 1848 revolution." },
  { code: "is", name: "Iceland",        continent: "Europe", fact: "Iceland's flag's red cross represents the volcanic fires beneath its glaciers." },
  { code: "ie", name: "Ireland",        continent: "Europe", fact: "Ireland's tricolor's white center symbolizes peace between the green Catholics and orange Protestants." },
  { code: "it", name: "Italy",          continent: "Europe", fact: "Italy's flag was inspired by the French tricolor brought by Napoleon in 1797." },
  { code: "xk", name: "Kosovo",         continent: "Europe", fact: "Kosovo's flag depicts its own map — one of only two countries to do so." },
  { code: "lv", name: "Latvia",         continent: "Europe", fact: "Latvia's flag is one of the world's oldest, mentioned in a 13th-century chronicle." },
  { code: "li", name: "Liechtenstein",  continent: "Europe", fact: "Liechtenstein added a crown to its flag in 1937 — to distinguish it from Haiti's." },
  { code: "lt", name: "Lithuania",      continent: "Europe", fact: "Lithuania's flag's yellow, green, red represent the sun, forests, and bloodshed for freedom." },
  { code: "lu", name: "Luxembourg",     continent: "Europe", fact: "Luxembourg's flag is nearly identical to the Netherlands' — just a slightly lighter blue." },
  { code: "mt", name: "Malta",          continent: "Europe", fact: "Malta's flag features the George Cross — awarded by King George VI for WWII bravery." },
  { code: "md", name: "Moldova",        continent: "Europe", fact: "Moldova is one of only three countries with a different design on the back of its flag." },
  { code: "mc", name: "Monaco",         continent: "Europe", fact: "Monaco's flag is the second smallest country's — and identical to Indonesia's." },
  { code: "me", name: "Montenegro",     continent: "Europe", fact: "Montenegro's flag features a golden double-headed eagle on red." },
  { code: "nl", name: "Netherlands",    continent: "Europe", fact: "The Dutch tricolor is the oldest tricolor flag in the world, dating to 1572." },
  { code: "mk", name: "North Macedonia", continent: "Europe", fact: "North Macedonia's flag features a stylized 'sun of liberty' with eight rays." },
  { code: "no", name: "Norway",         continent: "Europe", fact: "Norway's flag is technically a Danish flag with a blue cross overlaid." },
  { code: "pl", name: "Poland",         continent: "Europe", fact: "Poland's flag's white over red is derived from its medieval coat of arms." },
  { code: "pt", name: "Portugal",       continent: "Europe", fact: "Portugal's flag features an armillary sphere — a navigational tool from the Age of Discoveries." },
  { code: "ro", name: "Romania",        continent: "Europe", fact: "Romania's flag is nearly identical to Chad's — colors and proportions both close." },
  { code: "ru", name: "Russia",         continent: "Europe", fact: "Russia's white-blue-red tricolor was introduced by Peter the Great in 1696." },
  { code: "sm", name: "San Marino",     continent: "Europe", fact: "San Marino is the world's oldest republic, founded in 301 AD." },
  { code: "rs", name: "Serbia",         continent: "Europe", fact: "Serbia's flag features the Pan-Slavic colors and the country's coat of arms with a double-headed eagle." },
  { code: "sk", name: "Slovakia",       continent: "Europe", fact: "Slovakia's flag features a coat of arms with a double cross on three hills." },
  { code: "si", name: "Slovenia",       continent: "Europe", fact: "Slovenia's flag features Mount Triglav — the country's highest peak — in its coat of arms." },
  { code: "es", name: "Spain",          continent: "Europe", fact: "Spain's flag features a coat of arms with the Pillars of Hercules." },
  { code: "se", name: "Sweden",         continent: "Europe", fact: "Sweden's blue-and-yellow flag dates to the 16th century." },
  { code: "ch", name: "Switzerland",    continent: "Europe", fact: "Switzerland's flag is one of only two square national flags (the other is Vatican City)." },
  { code: "ua", name: "Ukraine",        continent: "Europe", fact: "Ukraine's flag depicts blue sky over a golden wheat field." },
  { code: "gb", name: "United Kingdom", continent: "Europe", fact: "The Union Jack combines the crosses of England, Scotland, and Saint Patrick (Ireland)." },
  { code: "va", name: "Vatican City",   continent: "Europe", fact: "Vatican City has one of only two square national flags." },

  // --- North America ---
  { code: "ag", name: "Antigua and Barbuda", continent: "North America", fact: "Its flag's V-shape and rising sun represent victory and a new era." },
  { code: "bs", name: "Bahamas",        continent: "North America", fact: "The Bahamas consists of over 700 islands and cays." },
  { code: "bb", name: "Barbados",       continent: "North America", fact: "Barbados' flag features the broken trident of Neptune — symbolizing independence." },
  { code: "bz", name: "Belize",         continent: "North America", fact: "Belize's flag is the only national flag with humans depicted prominently." },
  { code: "ca", name: "Canada",         continent: "North America", fact: "Canada's maple leaf flag was adopted in 1965 after a fierce parliamentary debate." },
  { code: "cr", name: "Costa Rica",     continent: "North America", fact: "Costa Rica abolished its army in 1948 and reinvested in education." },
  { code: "cu", name: "Cuba",           continent: "North America", fact: "Cuba's flag's lone star represents the freedom of its people." },
  { code: "dm", name: "Dominica",       continent: "North America", fact: "Dominica's flag features a sisserou parrot — its national bird." },
  { code: "do", name: "Dominican Republic", continent: "North America", fact: "It's the only flag in the world with the Bible depicted on its coat of arms." },
  { code: "sv", name: "El Salvador",    continent: "North America", fact: "El Salvador is the smallest country in Central America." },
  { code: "gd", name: "Grenada",        continent: "North America", fact: "Grenada's flag features a nutmeg — its main export, earning it the nickname 'Spice Isle'." },
  { code: "gt", name: "Guatemala",      continent: "North America", fact: "Guatemala's flag features the resplendent quetzal — its national bird." },
  { code: "ht", name: "Haiti",          continent: "North America", fact: "Haiti was the first independent Black-led republic, founded in 1804." },
  { code: "hn", name: "Honduras",       continent: "North America", fact: "Honduras' flag's five stars represent Central America's five original countries." },
  { code: "jm", name: "Jamaica",        continent: "North America", fact: "Jamaica's flag is the only national flag without red, white, or blue." },
  { code: "mx", name: "Mexico",         continent: "North America", fact: "Mexico's flag features an eagle eating a snake — fulfilling an Aztec prophecy." },
  { code: "ni", name: "Nicaragua",      continent: "North America", fact: "Nicaragua's flag is one of only two with the color purple (in its rainbow)." },
  { code: "pa", name: "Panama",         continent: "North America", fact: "Panama's flag's quartered design represents political balance: liberals and conservatives." },
  { code: "kn", name: "Saint Kitts and Nevis", continent: "North America", fact: "Its two stars represent hope and liberty." },
  { code: "lc", name: "Saint Lucia",    continent: "North America", fact: "Saint Lucia's flag features an isosceles triangle representing its iconic Pitons." },
  { code: "vc", name: "Saint Vincent and the Grenadines", continent: "North America", fact: "Its three green diamonds form a 'V' for Vincent." },
  { code: "tt", name: "Trinidad and Tobago", continent: "North America", fact: "Trinidad and Tobago is the birthplace of steel pan music and the limbo dance." },
  { code: "us", name: "United States",  continent: "North America", fact: "The US flag's 50 stars represent its states; the 13 stripes represent the original colonies." },

  // --- South America ---
  { code: "ar", name: "Argentina",      continent: "South America", fact: "Argentina's flag's 'Sun of May' commemorates a clear sky during a 1810 protest." },
  { code: "bo", name: "Bolivia",        continent: "South America", fact: "Bolivia is one of only two landlocked countries in South America." },
  { code: "br", name: "Brazil",         continent: "South America", fact: "Brazil's flag's stars depict the night sky over Rio on the day the republic was declared." },
  { code: "cl", name: "Chile",          continent: "South America", fact: "Chile is the longest country in the world from north to south." },
  { code: "co", name: "Colombia",       continent: "South America", fact: "Colombia's flag's yellow stripe is twice as wide as the others — symbolizing its mineral wealth." },
  { code: "ec", name: "Ecuador",        continent: "South America", fact: "Ecuador's flag features a condor — the largest flying bird in the world." },
  { code: "gy", name: "Guyana",         continent: "South America", fact: "Guyana's flag is called the 'Golden Arrowhead'." },
  { code: "py", name: "Paraguay",       continent: "South America", fact: "Paraguay is one of only three countries with a different design on the back of its flag." },
  { code: "pe", name: "Peru",           continent: "South America", fact: "Peru's flag's red stripes were inspired by the flamingos that flew over José de San Martín." },
  { code: "sr", name: "Suriname",       continent: "South America", fact: "Suriname is the smallest sovereign country in South America." },
  { code: "uy", name: "Uruguay",        continent: "South America", fact: "Uruguay's flag features its own 'Sun of May', similar to Argentina's." },
  { code: "ve", name: "Venezuela",      continent: "South America", fact: "Venezuela's flag's eight stars represent the provinces that fought for independence." },

  // --- Oceania ---
  { code: "au", name: "Australia",      continent: "Oceania", fact: "Australia's flag features the Southern Cross — a constellation visible in the Southern Hemisphere." },
  { code: "fj", name: "Fiji",           continent: "Oceania", fact: "Fiji's flag still features the British Union Jack despite proposals to change it." },
  { code: "ki", name: "Kiribati",       continent: "Oceania", fact: "Kiribati straddles the equator and the international date line." },
  { code: "mh", name: "Marshall Islands", continent: "Oceania", fact: "The Marshall Islands' flag's 24-pointed star represents its 24 electoral districts." },
  { code: "fm", name: "Micronesia",     continent: "Oceania", fact: "Micronesia's flag features four stars representing its four states." },
  { code: "nr", name: "Nauru",          continent: "Oceania", fact: "Nauru is the world's smallest island country — only 21 km²." },
  { code: "nz", name: "New Zealand",    continent: "Oceania", fact: "New Zealand's flag features the Southern Cross — like Australia's, but with red stars." },
  { code: "pw", name: "Palau",          continent: "Oceania", fact: "Palau's flag features a yellow disc — said to represent the moon at its fullest." },
  { code: "pg", name: "Papua New Guinea", continent: "Oceania", fact: "Papua New Guinea's flag features a bird-of-paradise and the Southern Cross." },
  { code: "ws", name: "Samoa",          continent: "Oceania", fact: "Samoa's flag features the Southern Cross with five stars instead of the usual four." },
  { code: "sb", name: "Solomon Islands", continent: "Oceania", fact: "The Solomon Islands' flag's five stars originally represented its five districts." },
  { code: "to", name: "Tonga",          continent: "Oceania", fact: "Tonga is the only Pacific nation that was never fully colonized by a foreign power." },
  { code: "tv", name: "Tuvalu",         continent: "Oceania", fact: "Tuvalu's flag features nine stars — one for each of its islands." },
  { code: "vu", name: "Vanuatu",        continent: "Oceania", fact: "Vanuatu's flag features a boar's tusk encircling two crossed namele leaves." },
];

module.exports = { COUNTRIES };
